Fix bug #2981 and other two implicit...
...declaration warnings I probably introduced in previous commits:

• notification_prefs.c:1285:2: warning: implicit declaration of function
  'filesel_select_file_open' [-Wimplicit-function-declaration]
• rssyl_prefs.c:110:2: warning: implicit declaration of function
  'filesel_select_file_open' [-Wimplicit-function-declaration]
• icalderivedproperty.c:374:4: warning: implicit declaration of function
  'icalproperty_add_parameters' [-Wimplicit-function-declaration]

;-)