Fix build on Hurd
Error was “mailimf_types_helper.c:1265:13: error: 'HOST_NAME_MAX'
undeclared (first use in this function); did you mean 'NAME_MAX'?”

Completes commit 3a482f4d25110e588ef58d5ee67fa4216a6b631d where this
define was used first.